<?php

/**
 * PluginClapTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginClapTable extends Doctrine_Table
{
  public function getObject($foreignTable, $foreignId)
  {
    $obj = $this->createQuery('c')->addWhere('c.foreign_table = ?', $foreignTable)->addWhere('c.foreign_id = ?', $foreignId)->fetchOne();
    if(!$obj)
    {
      $obj = new Clap();
      $obj->set('foreign_table', $foreignTable);
      $obj->set('foreign_id', $foreignId);
    }
    return $obj;
  }
  
  public function clapTo($foreignTable, $foreignId)
  {
    $clap = $this->getObject($foreignTable, $foreignId);
    if(!$clap->isNew())
    {
      Doctrine_Query::create()->update('Clap')->set('claps', 'claps + 1')->where('id = ?', $clap->getId())->execute();
      return $clap;
    }
    $clap->setClaps(1);
    $clap->save();
    return $clap;
  }
}